package main

import (
	"bufio"
	"compress/gzip"
	"embed"
	"strconv"
	"strings"
	"sync"
)

// Offline Bluetooth / OUI identification tables, generated by
// tools/gen_btdb.py from the Bluetooth SIG assigned numbers and the IEEE OUI
// registry. Loaded lazily on first lookup so process start stays cheap.

//go:embed btdb/*.tsv.gz
var btdbFS embed.FS

type btNames struct{ brand, full string }

type btdbTables struct {
	companies  map[int]btNames
	members    map[int]btNames
	services   map[int]string
	appearance map[int]string
	oui        map[uint32]string
}

var (
	btdbOnce sync.Once
	btdbData *btdbTables
)

func btdbLoad() *btdbTables {
	btdbOnce.Do(func() {
		t := &btdbTables{
			companies:  map[int]btNames{},
			members:    map[int]btNames{},
			services:   map[int]string{},
			appearance: map[int]string{},
			oui:        map[uint32]string{},
		}
		btdbRead("btdb/companies.tsv.gz", func(f []string) {
			if v, ok := btdbHex(f[0]); ok && len(f) >= 3 {
				t.companies[v] = btNames{f[1], f[2]}
			}
		})
		btdbRead("btdb/members.tsv.gz", func(f []string) {
			if v, ok := btdbHex(f[0]); ok && len(f) >= 3 {
				t.members[v] = btNames{f[1], f[2]}
			}
		})
		btdbRead("btdb/services.tsv.gz", func(f []string) {
			if v, ok := btdbHex(f[0]); ok && len(f) >= 2 {
				t.services[v] = f[1]
			}
		})
		btdbRead("btdb/appearance.tsv.gz", func(f []string) {
			if v, ok := btdbHex(f[0]); ok && len(f) >= 2 {
				t.appearance[v] = f[1]
			}
		})
		btdbRead("btdb/oui.tsv.gz", func(f []string) {
			if v, ok := btdbHex(f[0]); ok && len(f) >= 2 {
				t.oui[uint32(v)] = f[1]
			}
		})
		btdbData = t
	})
	return btdbData
}

func btdbHex(s string) (int, bool) {
	v, err := strconv.ParseUint(s, 16, 32)
	if err != nil {
		return 0, false
	}
	return int(v), true
}

// btdbRead streams one embedded gzip TSV; a missing or corrupt file simply
// yields no rows (lookups then report ok=false).
func btdbRead(name string, each func(fields []string)) {
	f, err := btdbFS.Open(name)
	if err != nil {
		return
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		return
	}
	defer gz.Close()
	sc := bufio.NewScanner(gz)
	for sc.Scan() {
		if line := sc.Text(); line != "" {
			each(strings.Split(line, "\t"))
		}
	}
}

// CompanyBrand returns the short brand and fuller name for a SIG company id.
func CompanyBrand(id int) (brand, full string, ok bool) {
	n, ok := btdbLoad().companies[id]
	return n.brand, n.full, ok
}

// MemberBrand returns the brand for a SIG member 16-bit service UUID.
func MemberBrand(uuid16 int) (brand, full string, ok bool) {
	n, ok := btdbLoad().members[uuid16]
	return n.brand, n.full, ok
}

// ServiceName returns the SIG name of an assigned 16-bit service UUID.
func ServiceName(uuid16 int) (string, bool) {
	n, ok := btdbLoad().services[uuid16]
	return n, ok
}

// AppearanceName resolves a GAP appearance value: the exact value first, then
// its category (value with the 6 subcategory bits cleared).
func AppearanceName(v int) (string, bool) {
	t := btdbLoad()
	if n, ok := t.appearance[v]; ok {
		return n, true
	}
	n, ok := t.appearance[v&^0x3F]
	return n, ok
}

// OUIBrand maps "AA:BB:CC:..." (any case, ':' or '-') to the registered
// vendor's brand. Malformed addresses report ok=false.
func OUIBrand(addr string) (string, bool) {
	if len(addr) < 8 {
		return "", false
	}
	var oui uint32
	for i := 0; i < 3; i++ {
		p := addr[i*3 : i*3+2]
		if i < 2 && addr[i*3+2] != ':' && addr[i*3+2] != '-' {
			return "", false
		}
		b, err := strconv.ParseUint(p, 16, 8)
		if err != nil {
			return "", false
		}
		oui = oui<<8 | uint32(b)
	}
	if len(addr) > 8 && addr[8] != ':' && addr[8] != '-' {
		return "", false
	}
	n, ok := btdbLoad().oui[oui]
	return n, ok
}
